STRINGS = {
    "Russian": {
        "m_1": "[1] Ссылки на подписку", "m_2": "[2] Настройки", "m_3": "[3] Парсить сейчас",
        "m_4": "[4] Язык", "m_0": "[0] Выход", "m_last": "Последний запуск: ",
        "s_1": "[1] Фильтр РОС. Серверов: ", "s_2": "[2] Лимит конфигов: ", "s_3": "[3] Тема: ",
        "s_4": "[4] Управление источниками", "s_5": "[5] Тип теста: ", "s_6": "[6] Фильтр дубликатов: ",
        "s_0": "[0] Назад", "on": "ВКЛ", "off": "ВЫКЛ",
        "src_1": "Список источников", "src_2": "Вкл/Выкл Репозиторий", "src_3": "Добавить свой источник",
        "src_all": "Всего: ", "repo": "Репозиторий: ", "enter": "Нажмите Enter...", "num_repo": "ID репозитория: ",
        "parsing": "Загрузка: ", "sub_reg": "ОБЫЧНЫЙ VPN:", "sub_white": "БЕЛЫЕ СПИСКИ:", "choice": "Номер темы: ",
        "never": "Никогда", "test_fast": "TCP Пинг", "test_tcp": "TLS Handshake (Точный)",
        "copy_reg": "[1] Копировать обычную", "copy_white": "[2] Копировать белую",
        "copied": "✓ Скопировано!", "copy_fail": "✗ Не удалось скопировать",
        "err_default": "Ошибка: Нельзя добавлять в дефолтные источники!",
        "enter_repo": "Название источника (при вводе существующего - добавит в него):",
        "enter_url": "Введите URL ссылку на подписку:", "smart_info": "Удалено дублей: "
    },
    "English": {
        "m_1": "[1] Subscription Links", "m_2": "[2] Settings", "m_3": "[3] Fetch Configs",
        "m_4": "[4] Language", "m_0": "[0] Exit", "m_last": "Last run: ",
        "s_1": "[1] Filter RU Servers: ", "s_2": "[2] Nodes Limit: ", "s_3": "[3] UI Theme: ",
        "s_4": "[4] Source Management", "s_5": "[5] Test Type: ", "s_6": "[6] Duplicates Filter: ",
        "s_0": "[0] Back", "on": "ON", "off": "OFF",
        "src_1": "Source List", "src_2": "Toggle Repository", "src_3": "Add custom source",
        "src_all": "Total: ", "repo": "Repository: ", "enter": "Press Enter...", "num_repo": "Repository ID: ",
        "parsing": "Fetching: ", "sub_reg": "STANDARD VPN:", "sub_white": "WHITE LISTS:", "choice": "Theme number: ",
        "never": "Never", "test_fast": "TCP Ping", "test_tcp": "TLS Handshake (Accurate)",
        "copy_reg": "[1] Copy regular link", "copy_white": "[2] Copy whitelist link",
        "copied": "✓ Copied!", "copy_fail": "✗ Failed to copy",
        "err_default": "Error: Cannot add to default sources!",
        "enter_repo": "Source name (if exists, will add to it):",
        "enter_url": "Enter subscription URL:", "smart_info": "Duplicates removed: "
    },
    "Chinese": {
        "m_1": "[1] 订阅链接", "m_2": "[2] 设置", "m_3": "[3] 立即抓取",
        "m_4": "[4] 语言", "m_0": "[0] 退出", "m_last": "上次运行: ",
        "s_1": "[1] 过滤俄罗斯服务器: ", "s_2": "[2] 配置限制: ", "s_3": "[3] 主题: ",
        "s_4": "[4] 来源管理", "s_5": "[5] 测试类型: ", "s_6": "[6] 重复过滤器: ",
        "s_0": "[0] 返回", "on": "开启", "off": "关闭",
        "src_1": "来源列表", "src_2": "开启/关闭 仓库", "src_3": "添加自定义来源",
        "src_all": "总计: ", "repo": "仓库: ", "enter": "按回车键...", "num_repo": "仓库 ID: ",
        "parsing": "正在抓取: ", "sub_reg": "普通 VPN:", "sub_white": "白名单:", "choice": "主题编号: ",
        "never": "从未", "test_fast": "TCP Ping", "test_tcp": "TLS 握手 (精确)",
        "copy_reg": "[1] 复制普通链接", "copy_white": "[2] 复制白名单链接",
        "copied": "✓ 已复制!", "copy_fail": "✗ 复制失败",
        "err_default": "错误：不能添加到默认来源！",
        "enter_repo": "来源名称（如果已存在，将添加到其中）：",
        "enter_url": "输入订阅 URL：", "smart_info": "重复项已删除: "
    }
}